import React, { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import SectionCard from '../components/SectionCard';
import LoadingSpinner from '../components/LoadingSpinner';
import { getArtifacts, createArtifact, deleteArtifact } from '../api/client';

function ArtifactTrackerPage() {
  const [artifacts, setArtifacts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [formData, setFormData] = useState({
    projectName: '',
    filePath: '',
    artifactType: 'frontend',
    purpose: '',
    bobSessionFile: '',
    status: 'completed',
    notes: ''
  });

  useEffect(() => {
    loadArtifacts();
  }, []);

  const loadArtifacts = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await getArtifacts();
      setArtifacts(response.artifacts || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.projectName.trim() || !formData.filePath.trim() || !formData.purpose.trim()) {
      setError('Project name, file path, and purpose are required');
      return;
    }

    setSubmitting(true);
    setError('');
    setSuccess('');

    try {
      await createArtifact(formData);
      setSuccess('Artifact added successfully!');
      setFormData({
        projectName: '',
        filePath: '',
        artifactType: 'frontend',
        purpose: '',
        bobSessionFile: '',
        status: 'completed',
        notes: ''
      });
      setShowForm(false);
      await loadArtifacts();
      
      setTimeout(() => setSuccess(''), 3000);
    } catch (err) {
      setError(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this artifact?')) {
      return;
    }

    try {
      await deleteArtifact(id);
      setSuccess('Artifact deleted successfully!');
      await loadArtifacts();
      setTimeout(() => setSuccess(''), 3000);
    } catch (err) {
      setError(err.message);
    }
  };

  const getStatusBadge = (status) => {
    const styles = {
      completed: 'bg-green-100 text-green-800',
      'in-progress': 'bg-yellow-100 text-yellow-800',
      pending: 'bg-gray-100 text-gray-800'
    };
    return styles[status] || styles.pending;
  };

  const getTypeBadge = (type) => {
    const styles = {
      frontend: 'bg-blue-100 text-blue-800',
      backend: 'bg-purple-100 text-purple-800',
      test: 'bg-green-100 text-green-800',
      documentation: 'bg-yellow-100 text-yellow-800',
      configuration: 'bg-gray-100 text-gray-800',
      deployment: 'bg-red-100 text-red-800',
      database: 'bg-indigo-100 text-indigo-800'
    };
    return styles[type] || styles.configuration;
  };

  // Calculate summary statistics
  const totalArtifacts = artifacts.length;
  const frontendArtifacts = artifacts.filter(a => a.artifactType === 'frontend').length;
  const backendArtifacts = artifacts.filter(a => a.artifactType === 'backend').length;
  const testArtifacts = artifacts.filter(a => a.artifactType === 'test').length;
  const documentationArtifacts = artifacts.filter(a => a.artifactType === 'documentation').length;

  return (
    <Layout>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-2">
            📦 Artifact Tracker
          </h1>
          <p className="text-gray-600">
            Track files and components generated by IBM Bob
          </p>
        </div>

        {/* Success Message */}
        {success && (
          <div className="mb-6 bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded">
            {success}
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
            {error}
          </div>
        )}

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
          <div className="card bg-gradient-to-br from-blue-50 to-blue-100 border-blue-200">
            <div className="text-center">
              <div className="text-3xl font-bold text-blue-600">{totalArtifacts}</div>
              <div className="text-sm text-gray-600 mt-1">Total Artifacts</div>
            </div>
          </div>
          <div className="card bg-gradient-to-br from-purple-50 to-purple-100 border-purple-200">
            <div className="text-center">
              <div className="text-3xl font-bold text-purple-600">{frontendArtifacts}</div>
              <div className="text-sm text-gray-600 mt-1">Frontend</div>
            </div>
          </div>
          <div className="card bg-gradient-to-br from-indigo-50 to-indigo-100 border-indigo-200">
            <div className="text-center">
              <div className="text-3xl font-bold text-indigo-600">{backendArtifacts}</div>
              <div className="text-sm text-gray-600 mt-1">Backend</div>
            </div>
          </div>
          <div className="card bg-gradient-to-br from-green-50 to-green-100 border-green-200">
            <div className="text-center">
              <div className="text-3xl font-bold text-green-600">{testArtifacts}</div>
              <div className="text-sm text-gray-600 mt-1">Tests</div>
            </div>
          </div>
          <div className="card bg-gradient-to-br from-yellow-50 to-yellow-100 border-yellow-200">
            <div className="text-center">
              <div className="text-3xl font-bold text-yellow-600">{documentationArtifacts}</div>
              <div className="text-sm text-gray-600 mt-1">Documentation</div>
            </div>
          </div>
        </div>

        {/* Add Artifact Button */}
        <div className="mb-6">
          <button
            className="btn-primary"
            onClick={() => setShowForm(!showForm)}
          >
            {showForm ? '✕ Cancel' : '➕ Add Artifact'}
          </button>
        </div>

        {/* Add Artifact Form */}
        {showForm && (
          <SectionCard title="Add New Artifact" className="mb-6">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Project Name *
                  </label>
                  <input
                    type="text"
                    name="projectName"
                    className="input-field w-full"
                    placeholder="e.g., smart-attendance-demo"
                    value={formData.projectName}
                    onChange={handleInputChange}
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Artifact Type *
                  </label>
                  <select
                    name="artifactType"
                    className="input-field w-full"
                    value={formData.artifactType}
                    onChange={handleInputChange}
                    required
                  >
                    <option value="frontend">Frontend</option>
                    <option value="backend">Backend</option>
                    <option value="test">Test</option>
                    <option value="documentation">Documentation</option>
                    <option value="configuration">Configuration</option>
                    <option value="deployment">Deployment</option>
                    <option value="database">Database</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  File Path *
                </label>
                <input
                  type="text"
                  name="filePath"
                  className="input-field w-full"
                  placeholder="e.g., src/components/UserDashboard.jsx"
                  value={formData.filePath}
                  onChange={handleInputChange}
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Purpose *
                </label>
                <input
                  type="text"
                  name="purpose"
                  className="input-field w-full"
                  placeholder="e.g., Main dashboard component for user interface"
                  value={formData.purpose}
                  onChange={handleInputChange}
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Bob Session Report Filename
                  </label>
                  <input
                    type="text"
                    name="bobSessionFile"
                    className="input-field w-full"
                    placeholder="e.g., frontend-implementation-2024-01-15.md"
                    value={formData.bobSessionFile}
                    onChange={handleInputChange}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Status
                  </label>
                  <select
                    name="status"
                    className="input-field w-full"
                    value={formData.status}
                    onChange={handleInputChange}
                  >
                    <option value="completed">Completed</option>
                    <option value="in-progress">In Progress</option>
                    <option value="pending">Pending</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Notes
                </label>
                <textarea
                  name="notes"
                  className="input-field w-full"
                  rows="3"
                  placeholder="Additional notes about this artifact..."
                  value={formData.notes}
                  onChange={handleInputChange}
                />
              </div>

              <div className="flex gap-3">
                <button
                  type="submit"
                  className="btn-primary"
                  disabled={submitting}
                >
                  {submitting ? 'Adding...' : 'Add Artifact'}
                </button>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={() => setShowForm(false)}
                >
                  Cancel
                </button>
              </div>
            </form>
          </SectionCard>
        )}

        {/* Artifacts List */}
        <SectionCard title="Tracked Artifacts">
          {loading ? (
            <LoadingSpinner message="Loading artifacts..." />
          ) : artifacts.length === 0 ? (
            <div className="text-center py-12">
              <div className="text-gray-400 text-5xl mb-4">📦</div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">
                No Artifacts Tracked Yet
              </h3>
              <p className="text-gray-600 mb-4">
                Start tracking files generated by IBM Bob to document your development process.
              </p>
              <button
                className="btn-primary"
                onClick={() => setShowForm(true)}
              >
                Add Your First Artifact
              </button>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Project
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      File Path
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Type
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Purpose
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Bob Session
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {artifacts.map((artifact) => (
                    <tr key={artifact.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">
                          {artifact.projectName}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <code className="text-sm text-blue-600 bg-blue-50 px-2 py-1 rounded">
                          {artifact.filePath}
                        </code>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${getTypeBadge(artifact.artifactType)}`}>
                          {artifact.artifactType}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="text-sm text-gray-900 max-w-xs truncate" title={artifact.purpose}>
                          {artifact.purpose}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-600">
                          {artifact.bobSessionFile || '-'}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusBadge(artifact.status)}`}>
                          {artifact.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <button
                          onClick={() => handleDelete(artifact.id)}
                          className="text-red-600 hover:text-red-900"
                          title="Delete artifact"
                        >
                          🗑️
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </SectionCard>

        {/* Info Card */}
        <div className="mt-6 card bg-blue-50 border-blue-200">
          <div className="flex items-start gap-4">
            <div className="text-3xl">💡</div>
            <div>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">
                About Artifact Tracking
              </h3>
              <p className="text-gray-700 text-sm">
                Use this tracker to document all files and components generated by IBM Bob during your development process. 
                This helps maintain a clear record of Bob's contributions to your project and serves as evidence for the hackathon.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default ArtifactTrackerPage;

// Made with Bob
